### ISSUE TITLE
Timeframe filter confusing when initially opening the leaderboard

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Hephaestus#107]
**Describe the bug**
When initially opening the leaderboard, it still looks like the time frame selector is applied. However, when switching to another time frame and back again to the original one, different data is shown (and now the browser URL shows the from/to URL parameters).
I therefore suspect the filter is not applied when loading the page initially.

**Expected behavior**
The UI should make clear that the filter is not yet applied (e.g. by having an empty dropdown option) since the current behaviour is confusing and is not clear if the filter is already applied on first page load or not.

**Screenshots**
URL is `https://hephaestus.ase.cit.tum.de/` without parameters, but filter looks like is is active:
![image](https://github.com/user-attachments/assets/8c24e8c6-4e67-4803-9093-927aa56232b4)
Data in the table does not seem to be filtered, however.

**Additional context**

**Comment by GODrums** [comment]
Thank you for noticing this!

Yes, you are completely correct about your assumption. The initial leaderboard (no params) currently displays the past 7 days.
This will be addressed in a fix ASAP!
