### ISSUE TITLE
Missing Review from Weekly PR Summary

### ISSUE THREAD

**Issue by DominikRemo** [ls1intum/Hephaestus#117]
**Describe the bug**
The tool does not count my review for the following Pull Request, despite it being completed within the relevant time frames: [PR Review Link](https://github.com/ls1intum/Artemis/pull/9475#pullrequestreview-2364995384). This review should have been counted for CW 41 but is not accounted for (it is also missing from CW 42).

**To Reproduce**
1.	Go to the tool’s summary page for [CW 41](https://hephaestus.ase.cit.tum.de/?after=2024-10-07&before=2024-10-13) and [CW 42](https://hephaestus.ase.cit.tum.de/?after=2024-10-14&before=2024-10-14).
2.	Check the list of counted reviews.
3.	Search for the reviewer (Dominik Remo) associated with [The PR Review](https://github.com/ls1intum/Artemis/pull/9475#pullrequestreview-2364995384)
4.	The review is missing from the counted reviews in both weeks.

**Expected behavior**
The review for the PR should have been counted towards my total review score for CW 41.

**Additional context**
This issue may impact the accuracy of review scores and could affect multiple users. The review was completed and visible on GitHub, but the tool failed to recognize it for scoring. It might be useful to check the review processing logic or any filters applied when counting reviews in weekly summaries.

**Comment by GODrums** [comment]
Thank you for informing us!

We were made aware of this issue earlier today and are working with highest priority on fixing this! I am currently testing possible solutions in #118.

We will make an additional post on Slack as soon as the fix has been pushed.
