### ISSUE TITLE
Integrate Spotless for Java

### ISSUE THREAD

**Issue by FelixTJDietrich** [ls1intum/Hephaestus#123]
**Is your feature request related to a problem? Please describe.**
We need a consistent formatter for Java similar to prettier in JS

**Describe the solution you'd like**
I came across [Spotless](https://github.com/diffplug/spotless) used by the github-api library that we are using.
We should integrate it similarly to prettier and have it part of the code quality workflow.

**Describe alternatives you've considered**
To be considered.

**Comment by GODrums** [comment]
Love this, let's do it! 👍 
Alternatively, there is also a Prettier-plugin for Java, if we are rather interesting in keeping the same formatter for all sub-projects in the repo: https://github.com/jhipster/prettier-java
