### ISSUE TITLE
Setup FastAPI Intelligence Service

### ISSUE THREAD

**Issue by FelixTJDietrich** [ls1intum/Hephaestus#31]
**Is your feature request related to a problem? Please describe.**

For interfacing with LangChain and other ML services, it is easier to use Python. FastAPI offers a good framework to build up an intelligence service.

**Describe the solution you'd like**
- In `server/intelligence-service`, create a new FastAPI service.
- Use poetry to manage dependencies.
- Research best practices and document it in the `docs` (e.g. https://github.com/zhanymkanov/fastapi-best-practices)
- Create a hello world endpoint following best practices.

**Describe alternatives you've considered**
- Flask
- Django

I have more experience with FastAPI and it will work well for us.

**Additional context**
- https://fastapi.tiangolo.com/
- https://fastapi.tiangolo.com/learn/

**Comment by milesha** [comment]
Done and merged 👍🏼
